kafka:
  bootstrap-servers: localhost:9092
  topic:
    mercury: mercury.t

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.blockchain.mercury.model,org.springframework
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      group-id: foo
      topic:
        mercury: mercury.t